# Generated by Django 5.2.3 on 2025-06-15 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prova.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_nome', models.CharField(max_length=200)),
                ('candidato_cpf', models.CharField(max_length=14, unique=True)),
                ('candidato_email', models.EmailField(max_length=254)),
                ('candidato_telefone', models.CharField(max_length=15)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tempo_limite', models.IntegerField(default=3600)),
                ('questoes', models.ManyToManyField(to='prova.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='prova.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prova.alternativa')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prova.prova')),
            ],
            options={
                'unique_together': {('prova', 'alternativa')},
            },
        ),
    ]
