# Generated by Django 5.2.3 on 2025-06-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prova.categoria'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='candidato_cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='questao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prova.categoria'),
        ),
    ]
