# Generated by Django 5.2.3 on 2025-06-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0002_prova_categoria_alter_prova_candidato_cpf_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resposta',
            new_name='EscolhaCandidato',
        ),
    ]
