# Generated by Django 5.2.3 on 2025-06-23 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0003_rename_resposta_escolhacandidato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterUniqueTogether(
            name='prova',
            unique_together={('candidato_cpf', 'categoria')},
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição geral do tópico')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='prova.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('texto_teorico', models.TextField(help_text='Conteúdo teórico detalhado do subtema')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='prova.topico')),
            ],
        ),
    ]
